# Generated by Django 3.2.9 on 2021-11-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='movie/actor/images')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(to='pinterest.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='pinterest.Categories'),
        ),
        migrations.AddField(
            model_name='series',
            name='casts',
            field=models.ManyToManyField(to='pinterest.Actor'),
        ),
        migrations.AddField(
            model_name='series',
            name='categories',
            field=models.ManyToManyField(to='pinterest.Categories'),
        ),
    ]
